global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sd-api'
    static_configs:
      - targets: ['sd-api:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
